version: '3'
services:
  redis:
    container_name: redis
    restart: always
    image: redis:alpine
    ports:
      - 6379:6379
  postgres:
    container_name: postgres
    image: postgres:alpine
    restart: always
    volumes:
      - ${HOME}/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
