version: "3"
services:
  redis:
    container_name: redis
    restart: always
    image: redis:alpine
    ports:
      - 6379:6379
  postgres:
    container_name: postgres
    image: postgres:13-alpine
    restart: always
    volumes:
      - ${HOME}/postgres/data:/var/lib/postgresql/data
      - ${HOME}/postgres/logs:/var/log/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9-management
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=dev
      
