version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:13-alpine
    restart: always
    volumes:
      - ${HOME}/postgres/data:/var/lib/postgresql/data
      - ${HOME}/postgres/logs:/var/log/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: always
    hostname: rabbitmq
    volumes:
      - ./.services/rabbitmq/mnesia:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
      - 5552:5552
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=dev