version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:13-alpine
    restart: always
    volumes:
      - ${HOME}/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
