version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:13-alpine
    restart: always
    volumes:
      - ${HOME}/postgres/data:/var/lib/postgresql/data
      - ${HOME}/postgres/logs:/var/log/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  rabbitmq1:
    container_name: rabbitmq1
    image: rabbitmq:3-management
    restart: always
    hostname: rabbitmq1
    volumes:
      - ${HOME}/rabbitmq/mnesia1:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
    ports:
      - 5672:5672
      - 15672:15672
      - 5552:5552
    environment:
      - RABBITMQ_ERLANG_COOKIE=123123123
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=dev
      - RABBITMQ_NODENAME=rabbitmq1
  rabbitmq2:
    container_name: rabbitmq2
    image: rabbitmq:3-management
    restart: always
    hostname: rabbitmq2
    depends_on:
      - rabbitmq1
    volumes:
      - ${HOME}/rabbitmq/mnesia2:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
    links:
      - rabbitmq1
    ports:
      - 5553:5552
    environment:
      - RABBITMQ_ERLANG_COOKIE=123123123
      - RABBITMQ_NODENAME=rabbitmq2
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=dev
